services:
  postgres:
    image: postgres
    container_name: teamup-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: teamup_owner
      POSTGRES_PASSWORD: npg_xPF9W1rNojTd
      POSTGRES_DB: teamup
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data:
